import type { ColorTheme } from "@/stores/types";

export const THEMES: ColorTheme[] = [
  {
    id: "classic",
    name: "Classic",
    colors: {
      background: "#FFFFFF",
      text: "#1A1A1A",
      sunday: "#DC2626",
      saturday: "#2563EB",
      holidayMark: "#DC2626",
      headerRule: "#D1D5DB",
      gridRule: "#E5E7EB",
      weekdayHeader: "#6B7280",
      monthLabel: "#111827",
    },
  },
  {
    id: "monochrome",
    name: "Monochrome",
    colors: {
      background: "#FFFFFF",
      text: "#1A1A1A",
      sunday: "#4B5563",
      saturday: "#6B7280",
      holidayMark: "#374151",
      headerRule: "#D1D5DB",
      gridRule: "#E5E7EB",
      weekdayHeader: "#9CA3AF",
      monthLabel: "#374151",
    },
  },
  {
    id: "dark",
    name: "Dark",
    colors: {
      background: "#1F2937",
      text: "#F9FAFB",
      sunday: "#FCA5A5",
      saturday: "#93C5FD",
      holidayMark: "#FCA5A5",
      headerRule: "#4B5563",
      gridRule: "#374151",
      weekdayHeader: "#9CA3AF",
      monthLabel: "#F3F4F6",
    },
  },
  {
    id: "cream",
    name: "Cream",
    colors: {
      background: "#FFFBEB",
      text: "#78350F",
      sunday: "#DC2626",
      saturday: "#1D4ED8",
      holidayMark: "#B91C1C",
      headerRule: "#D6D3D1",
      gridRule: "#E7E5E4",
      weekdayHeader: "#A8A29E",
      monthLabel: "#44403C",
    },
  },
  {
    id: "forest",
    name: "Forest",
    colors: {
      background: "#1A2E1A",
      text: "#D1FAE5",
      sunday: "#FCA5A5",
      saturday: "#93C5FD",
      holidayMark: "#FCA5A5",
      headerRule: "#365336",
      gridRule: "#2D4A2D",
      weekdayHeader: "#86EFAC",
      monthLabel: "#ECFDF5",
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    colors: {
      background: "#FFFFFF",
      text: "#9CA3AF",
      sunday: "#6B7280",
      saturday: "#9CA3AF",
      holidayMark: "#6B7280",
      headerRule: "#F3F4F6",
      gridRule: "#F9FAFB",
      weekdayHeader: "#D1D5DB",
      monthLabel: "#6B7280",
    },
  },
];
